# Generated by Django 3.0.7 on 2020-06-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='titre',
            new_name='sujet',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='tel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
