# Generated by Django 3.0.7 on 2020-06-21 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='nom',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='apartment',
            name='douche',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='n_win',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='superficie',
            field=models.FloatField(null=True),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='cat_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='cat_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Catprojet', to='website.CatProjet'),
        ),
    ]
